# DSPark — editor page embedder (script mode).
#
#   cmake -DINPUT=<editor.html> -DOUTPUT=<header.h> -DVARIABLE=<name> \
#         -P DSParkEmbedEditor.cmake
#
# Reads the HTML page, inlines every local stylesheet and script it
# references — develop your UI as ordinary separate files, ship one
# self-contained C++ raw string:
#
#   <link rel="stylesheet" href="editor.css">  ->  <style>...file...</style>
#   <script src="editor.js"></script>          ->  <script>...file...</script>
#
# (double-quoted relative paths, resolved against the HTML's directory;
# absolute http(s) URLs are left untouched), then writes a header defining
#   inline constexpr char <VARIABLE>[] = R"dspkembed(...)dspkembed";
#
# Normally driven by dspark_embed_editor() / dspark_add_plugin(EDITOR_HTML)
# in DSParkPlugin.cmake, which also wire up the dependencies so editing any
# of the files regenerates the header on the next build.

if(NOT INPUT OR NOT OUTPUT OR NOT VARIABLE)
    message(FATAL_ERROR "DSParkEmbedEditor: INPUT, OUTPUT and VARIABLE are required")
endif()

file(READ "${INPUT}" page)
get_filename_component(page_dir "${INPUT}" DIRECTORY)

function(_dspark_read_asset path out_var)
    if(path MATCHES "^[a-zA-Z][a-zA-Z0-9+.-]*:")   # absolute URL: leave alone
        set(${out_var} "" PARENT_SCOPE)
        return()
    endif()
    set(full "${page_dir}/${path}")
    if(NOT EXISTS "${full}")
        message(FATAL_ERROR "DSParkEmbedEditor: '${path}' referenced by "
                            "${INPUT} not found at ${full}")
    endif()
    file(READ "${full}" content)
    set(${out_var} "${content}" PARENT_SCOPE)
endfunction()

# Inline stylesheets.
while(page MATCHES "<link[^>]*href=\"([^\"]+)\"[^>]*>")
    set(tag "${CMAKE_MATCH_0}")
    set(href "${CMAKE_MATCH_1}")
    if(NOT tag MATCHES "stylesheet")
        message(FATAL_ERROR "DSParkEmbedEditor: only rel=\"stylesheet\" links are "
                            "supported, found: ${tag}")
    endif()
    _dspark_read_asset("${href}" css)
    if(css STREQUAL "")
        message(FATAL_ERROR "DSParkEmbedEditor: external stylesheet URLs cannot be "
                            "embedded: ${href}")
    endif()
    string(REPLACE "${tag}" "<style>\n${css}</style>" page "${page}")
endwhile()

# Inline scripts (src form only; inline <script> blocks pass through).
while(page MATCHES "<script[^>]*src=\"([^\"]+)\"[^>]*>[ \t\r\n]*</script>")
    set(tag "${CMAKE_MATCH_0}")
    set(src "${CMAKE_MATCH_1}")
    _dspark_read_asset("${src}" js)
    if(js STREQUAL "")
        message(FATAL_ERROR "DSParkEmbedEditor: external script URLs cannot be "
                            "embedded: ${src}")
    endif()
    string(REPLACE "${tag}" "<script>\n${js}</script>" page "${page}")
endwhile()

if(page MATCHES "\\)dspkembed\"")
    message(FATAL_ERROR "DSParkEmbedEditor: the page contains the raw-string "
                        "delimiter ')dspkembed\"' and cannot be embedded")
endif()

get_filename_component(input_name "${INPUT}" NAME)
file(WRITE "${OUTPUT}"
"// Generated by DSPark dspark_embed_editor() from ${input_name} - do not edit.
#pragma once

inline constexpr char ${VARIABLE}[] = R\"dspkembed(${page})dspkembed\";
")

message(STATUS "DSParkEmbedEditor: ${OUTPUT} (<- ${input_name})")
