#!/usr/bin/env python3
"""DSPark single-header amalgamator.

Produces `dspark_single_header.hpp`: the whole framework in one file, in
correct dependency order, with internal includes stripped and system includes
deduplicated at the top. Usage:

    python tools/amalgamate.py [output_path]

The include order is taken from DSPark.h, so the umbrella header remains the
single source of truth for module ordering.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
UMBRELLA = ROOT / "DSPark.h"

INCLUDE_LOCAL = re.compile(r'^\s*#include\s+"([^"]+)"')
INCLUDE_SYSTEM = re.compile(r'^\s*#include\s+<([^>]+)>')
PRAGMA_ONCE = re.compile(r'^\s*#pragma\s+once')
IF_DIRECTIVE = re.compile(r'^\s*#\s*if(def|ndef)?\b')
ENDIF_DIRECTIVE = re.compile(r'^\s*#\s*endif\b')


def collect_order(umbrella_text):
    """Local include paths in DSPark.h order (IO kept, guarded later)."""
    order = []
    for line in umbrella_text.splitlines():
        m = INCLUDE_LOCAL.match(line)
        if m and m.group(1) not in order:
            order.append(m.group(1))
    return order


def main():
    out_path = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "dspark_single_header.hpp"

    umbrella_text = UMBRELLA.read_text(encoding="utf-8")
    headers = collect_order(umbrella_text)

    system_includes = []
    bodies = []
    emitted = set()

    def emit(rel):
        if rel in emitted:
            return
        emitted.add(rel)
        path = ROOT / rel
        text = path.read_text(encoding="utf-8")
        body_lines = [f"// ===== {rel} ====="]
        if_depth = 0
        for line in text.splitlines():
            if PRAGMA_ONCE.match(line):
                continue
            if IF_DIRECTIVE.match(line):
                if_depth += 1
            elif ENDIF_DIRECTIVE.match(line):
                if_depth -= 1
            lm = INCLUDE_LOCAL.match(line)
            if lm:
                # Resolve relative to the including header, emit dependency first
                dep = (path.parent / lm.group(1)).resolve().relative_to(ROOT)
                emit(str(dep).replace("\\", "/"))
                continue
            sm = INCLUDE_SYSTEM.match(line)
            if sm:
                # Only hoist unconditional system includes. Includes nested in
                # #if blocks are platform-specific (<arm_neon.h>, <immintrin.h>,
                # ...) and must stay in place with their guards.
                if if_depth == 0:
                    if sm.group(1) not in system_includes:
                        system_includes.append(sm.group(1))
                    continue
            body_lines.append(line)
        bodies.append("\n".join(body_lines))

    io_headers = [h for h in headers if h.startswith("IO/")]
    core_headers = [h for h in headers if not h.startswith("IO/")]

    for h in core_headers:
        emit(h)

    # IO is emitted separately so both its bodies AND its system includes
    # (<fstream>, <filesystem> — absent on bare-metal) sit behind the
    # DSPARK_NO_FILE_IO guard.
    core_system_count = len(system_includes)
    io_bodies_start = len(bodies)
    for h in io_headers:
        emit(h)
    io_bodies = bodies[io_bodies_start:]
    del bodies[io_bodies_start:]
    io_system = system_includes[core_system_count:]
    core_system = system_includes[:core_system_count]

    parts = [
        "// DSPark — single-header amalgamation (generated by tools/amalgamate.py)",
        "// Copyright (c) 2026 Cristian Moresi — MIT License",
        "// Do not edit: regenerate from the canonical headers instead.",
        "#pragma once",
        "",
    ]
    parts += [f"#include <{inc}>" for inc in sorted(core_system)]
    parts.append("")
    parts += bodies
    if io_bodies:
        parts.append("#ifndef DSPARK_NO_FILE_IO")
        parts += [f"#include <{inc}>" for inc in sorted(set(io_system) - set(core_system))]
        parts += io_bodies
        parts.append("#endif // DSPARK_NO_FILE_IO")

    out_path.write_text("\n".join(parts) + "\n", encoding="utf-8")
    print(f"Wrote {out_path} ({out_path.stat().st_size // 1024} KiB, "
          f"{len(emitted)} headers, {len(system_includes)} system includes)")


if __name__ == "__main__":
    main()
