// DSPark - Professional Audio DSP Framework
// Copyright (c) 2026 Cristian Moresi - MIT License

// Rebuild the fixed 1x continuous reconstruction/projection bank:
//   c++ -std=c++20 -O2 -I. tools/generate_stereo_color.cpp -o generate_stereo_color
//   ./generate_stereo_color Core/detail/StereoColorCoefficients.h
// Uses the same Core FIR/window and FFT implementations as other DSPark filters.
// The dense grid below is coefficient design only, never audio processing.
#include "../Core/FFT.h"
#include "../Core/FIRFilter.h"
#include <array>
#include <cmath>
#include <complex>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <numbers>
#include <vector>

namespace
{
constexpr int half = 128, grid = 64, fftSize = 131072;
constexpr double pi = std::numbers::pi_v<double>;

template <int Count> auto fitMatrix()
{
    constexpr int count = Count;
    using Matrix = std::array<std::array<double, count>, count>;
    Matrix chebyshev{}, fit{};
    chebyshev[0][0] = 1;
    chebyshev[1][0] = -1;
    chebyshev[1][1] = 2;
    for (int j = 2; j < count; ++j)
        for (int k = 0; k <= j; ++k)
            chebyshev[j][k] = (k ? 4 * chebyshev[j - 1][k - 1] : 0) -
                               2 * chebyshev[j - 1][k] - chebyshev[j - 2][k];
    for (int k = 0; k < count; ++k)
        for (int i = 0; i < count; ++i)
            for (int j = 0; j < count; ++j)
                fit[k][i] += chebyshev[j][k] * std::cos(j * pi * (i + .5) / count) *
                             (j ? 2. : 1.) / count;
    return fit;
}

// Eight-point interpolation of the dense, smooth design grid. Unlike the
// runtime reconstruction this operates only on fixed filter coefficients.
double sample(const std::vector<double> &values, double time)
{
    const double position = time * grid;
    const int first = static_cast<int>(std::floor(position)) - 3;
    double result = 0;
    for (int i = 0; i < 8; ++i)
    {
        double weight = 1;
        for (int j = 0; j < 8; ++j)
            if (i != j)
                weight *= (position - (first + j)) / (i - j);
        result += weight * values[2 * ((first + i + fftSize) % fftSize)];
    }
    return result;
}

template <int Count>
void writeBank(std::ostream &out, const std::vector<double> &kernel, int taps, bool projection)
{
    constexpr int count = Count;
    const auto fit = fitMatrix<count>();
    out << "{{\n";
    for (int k = 0; k < count; ++k)
    {
        out << "    {{\n        ";
        for (int lag = 0; lag < taps; ++lag)
        {
            double coefficient = 0;
            for (int i = 0; i < count; ++i)
            {
                const double t = (1 + std::cos(pi * (i + .5) / count)) / 2;
                coefficient += fit[k][i] * sample(kernel, lag - half + (projection ? -t : t));
            }
            out << coefficient;
            if (lag + 1 < taps) out << ',' << ((lag + 1) % 4 ? " " : "\n        ");
        }
        out << "\n    }}" << (k + 1 < count ? ",\n" : "\n");
    }
    out << "}}";
}

std::complex<double> difference(double angle)
{
    const double s = std::sin(angle / 2);
    return {2 * s * s, std::sin(angle)}; // 1 - exp(-i*angle), stable near zero.
}
} // namespace

int main(int argc, char **argv)
{
    if (argc != 2)
    {
        std::cerr << "Usage: generate_stereo_color OUTPUT_HEADER\n";
        return 1;
    }
    std::ofstream out(argv[1], std::ios::binary);
    if (!out) return 2;
    out << std::setprecision(std::numeric_limits<double>::max_digits10);
    out << "// DSPark - Professional Audio DSP Framework\n"
           "// Copyright (c) 2026 Cristian Moresi - MIT License\n\n"
           "#pragma once\n\n"
           "/** @file StereoColorCoefficients.h\n"
           " * @brief Fixed source-rate continuous color integration filters.\n"
           " * Generated by tools/generate_stereo_color.cpp; do not hand edit.\n"
           " * Kaiser beta 18.5, cutoff 0.475 Fs, support +/-128 samples;\n"
           " * degree-seven reconstruction and moment projection.\n"
           " * Chebyshev fits on each unit interval. Projection\n"
           " * includes the source-clock DC correction for S=1,2,4,8.\n"
           " * Shared read-only payload: 82496 bytes, independent of instances.\n"
           " */\n#include <array>\n\nnamespace dspark::detail::stereo_color_coefficients\n{\n"
           "inline constexpr int powers = 8, moments = 8, latency = 256;\n"
           "inline constexpr std::array<std::array<double, 257>, powers> reconstruction";
    const auto taps = dspark::FIRDesign<double>::lowPass(grid, .475, 2 * half * grid + 1, 18.5);
    std::vector<double> kernel(2 * fftSize);
    for (int i = 0; i < static_cast<int>(taps.size()); ++i)
        kernel[2 * ((i - half * grid + fftSize) % fftSize)] = grid * taps[i];
    writeBank<8>(out, kernel, 257, false);
    out << ";\ninline constexpr std::array<std::array<std::array<double, 258>, moments>, 4> projection{{\n";
    dspark::FFTComplex<double> fft(fftSize);
    fft.forward(kernel.data());
    for (int source : {1, 2, 4, 8})
    {
        auto corrected = kernel;
        constexpr double q = .9995;
        const double pole = std::pow(q, source);
        for (int i = 0; i < fftSize; ++i)
        {
            const double frequency = double(i <= fftSize / 2 ? i : i - fftSize) * grid / fftSize;
            const double w = 2 * pi * frequency;
            std::complex<double> ratio{};
            if (i == 0)
                ratio = (1 - pole) / (source * (1 - q));
            else if (std::abs(frequency) < .5)
            {
                const auto a = difference(w / source), b = difference(w);
                ratio = a * ((1 - pole) + pole * b) / (((1 - q) + q * a) * b);
            }
            const auto value = std::complex<double>(kernel[2 * i], kernel[2 * i + 1]) * ratio;
            corrected[2 * i] = value.real();
            corrected[2 * i + 1] = value.imag();
        }
        fft.inverse(corrected.data());
        writeBank<8>(out, corrected, 258, true);
        out << (source != 8 ? ",\n" : "\n");
    }
    out << "}};\n} // namespace dspark::detail::stereo_color_coefficients\n";
    return out ? 0 : 3;
}
